// <auto-generated />
using System;
using EatWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EatWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261005014658_AddMensajesRapidos")]
    partial class AddMensajesRapidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EatWeb.Models.HistorialMensajeRapido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnviadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstacionId")
                        .HasColumnType("integer");

                    b.Property<string>("GarzonId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Leido")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LeidoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MensajeRapidoId")
                        .HasColumnType("integer");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstacionId");

                    b.HasIndex("GarzonId");

                    b.HasIndex("MensajeRapidoId");

                    b.HasIndex("RestauranteId", "EstacionId", "EnviadoEn");

                    b.ToTable("HistorialMensajeRapido");
                });

            modelBuilder.Entity("EatWeb.Models.MensajeRapido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstacionId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EstacionId");

                    b.HasIndex("RestauranteId", "EstacionId");

                    b.ToTable("MensajeRapido");
                });

            modelBuilder.Entity("EatWeb.Models.HistorialMensajeRapido", b =>
                {
                    b.HasOne("EatWeb.Models.MensajeRapido", "MensajeRapido")
                        .WithMany("Historial")
                        .HasForeignKey("MensajeRapidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatWeb.Models.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EatWeb.Models.Estacion", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EatWeb.Models.ApplicationUser", "Garzon")
                        .WithMany()
                        .HasForeignKey("GarzonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Estacion");

                    b.Navigation("Garzon");

                    b.Navigation("MensajeRapido");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("EatWeb.Models.MensajeRapido", b =>
                {
                    b.HasOne("EatWeb.Models.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EatWeb.Models.Estacion", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estacion");

                    b.Navigation("Restaurante");
                });
#pragma warning restore 612, 618
        }
    }
}
